apiVersion: policies.kyverno.io/v1alpha1
kind: ImageValidatingPolicy
metadata:
  name: verify-acr-images
spec:
  failurePolicy: Fail

  webhookConfiguration:
    timeoutSeconds: 30

  evaluation:
    background:
      enabled: false

  validationActions:
    - Deny

  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: sample-api

  matchImageReferences:
    - glob: "acrdevsecopsrk964.azurecr.io/*"

  credentials:
    allowInsecureRegistry: false
    providers:
      - default
      - azure
    secrets:
      - acr-kyverno

  attestors:
    - name: githubactions
      cosign:
        keyless:
          identities:
            - issuer: "https://token.actions.githubusercontent.com"
              subjectRegExp: "https://github.com/cognoz/devsecops-azure-lab/.github/workflows/main-workflow.yml@refs/heads/.*"

        ctlog:
          url: "https://rekor.sigstore.dev"

  validationConfigurations:
    required: true
    mutateDigest: false
    verifyDigest: false

  validations:
    - expression: >-
        images.containers
          .map(image, verifyImageSignatures(image, [attestors.githubactions]))
          .all(e, e > 0)
      message: >-
        Images from acrdevsecopsrk964.azurecr.io must be signed
        by the approved GitHub Actions workflow.
